"""add cancellation reason and request date to order

Revision ID: 0194abdb2fa3
Revises: 4429ba8f4516
Create Date: 2025-06-02 21:47:25.011715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0194abdb2fa3'
down_revision = '4429ba8f4516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_requested_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('cancellation_requested_at')
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
