"""Add delivered_api_at and received_at to Order model

Revision ID: 4429ba8f4516
Revises: dad7585956bb
Create Date: 2025-05-22 16:17:42.254382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4429ba8f4516'
down_revision = 'dad7585956bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_api_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('received_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('received_at')
        batch_op.drop_column('delivered_api_at')

    # ### end Alembic commands ###
