"""Add shipped_at to Shipment model

Revision ID: ec16867a47aa
Revises: 3b4021d5d69c
Create Date: 2025-05-21 14:14:23.467380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec16867a47aa'
down_revision = '3b4021d5d69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipped_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('shipped_at')

    # ### end Alembic commands ###
